services:

  redis:
    image: redis:8
    command: sh -c 'redis-server --requirepass "$REDIS_PASSWORD"'
    environment:
      REDIS_PASSWORD: pinglow
    ports:
      - "6379:6379"

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_DB: pinglow
      POSTGRES_USER: pinglow
      POSTGRES_PASSWORD: pinglow
      REDIS_PASSWORD: pinglow
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.3
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"

volumes:
  timescale-data:
 