{{- if not .Values.redis.secretName }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "pinglow.redis.secretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pinglow.redis.secretName" . }}
  labels:
    app: redis
type: Opaque
data:
  REDIS_PASSWORD: {{ if and $secret $secret.data (hasKey $secret.data "REDIS_PASSWORD") }}{{ index $secret.data "REDIS_PASSWORD" | quote }}{{ else }}{{ randAlphaNum 32 | b64enc | quote }}{{ end }}
{{- end }}