apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scripts.pinglow.io
spec:
  group: pinglow.io
  names:
    plural: scripts
    singular: script
    kind: Script
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - language
                - content
              properties:
                language:
                  type: string
                  enum:
                    - Python
                    - Bash
                content:
                  type: string
                python_requirements:
                  type: array
                  items:
                    type: string
                  description: |
                    Optional pip-style requirements. Only used if language is 'python'
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: checks.pinglow.io
spec:
  group: pinglow.io
  names:
    plural: checks
    singular: check
    kind: Check
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                passive:
                  type: boolean
                  default: false
                scriptRef:
                  type: string
                interval:
                  type: integer
                  description: "Interval at which to run the check, in seconds"
                secretRefs:
                  type: array
                  items:
                    type: string
                telegramChannelRefs:
                  type: array
                  items:
                    type: string
                  description: Names of TelegramChannel resources to use
                muteNotifications:
                  type: boolean
                  description: whether notifications are muted
                muteNotificationsUntil:
                  type: string
                  format: date-time
                  description: RFC 3339 timestamp indicating when to resume notifications.
              x-kubernetes-validations:
                - rule: "self.passive == true || (has(self.scriptRef) && has(self.interval))"
                  message: "An active check must have the scriptRef and interval defined."

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: telegramchannels.pinglow.io
spec:
  group: pinglow.io
  names:
    plural: telegramchannels
    singular: telegramchannel
    kind: TelegramChannel
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [chatId, botTokenRef]
              properties:
                chatId:
                  type: string
                botTokenRef:
                  type: string
                  description: Name of the Kubernetes Secret containing `botToken`
