apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinglow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pinglow
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["pinglow.io"]
    resources: ["checks", "scripts", "telegramchannels"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["pinglow.io"]
    resources: ["checks/status", "scripts/status", "telegramchannels/status"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pinglow
subjects:
  - kind: ServiceAccount
    name: pinglow
roleRef:
  kind: Role
  name: pinglow
  apiGroup: rbac.authorization.k8s.io
