{{- if and .Values.timescaledb.enabled (not .Values.timescaledb.existingSecret) }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "pinglow.timescaledb.secretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pinglow.timescaledb.secretName" . }}
  labels:
    app: {{ include "pinglow.timescaledb.fullname" . }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.timescaledb.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ if $secret }}{{ index $secret.data "POSTGRES_PASSWORD" | quote }}{{ else }}{{ randAlphaNum 32 | b64enc | quote }}{{ end }}
  POSTGRES_DB: {{ .Values.timescaledb.database | b64enc | quote }}
{{- end }}